import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../components/layout'
// import { GetServerSideProps } from "next";
// import { getDatabase } from "../src/utils/database"

const Home: NextPage = () => {
  return (
    <Layout>
      <div>
        <Head>
          <title>Games-Catalog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1>Coucou</h1>
        </main>
      </div>
    </Layout>

  )
}


// export const getServerSideProps: GetServerSideProps = async () => {
//   const mongodb = await getDatabase();

//   const games = await mongodb.db().collection("games").find().toArray();
//   console.log(games);


//   return {
//     props: {
//       games: games
//     }
//   };
// }

export default Home
